defaultEnv: sit
environments:
  sit:
    cat-facts-api:
      base_url: https://catfact.ninja
      endpoints:
        facts: /fact
        breeds: /breeds
    human-resources-api:
      base_url: https://reqres.in
      endpoints:
        create_employee: /api/users
  uat:
    cat-facts-api:
      base_url: https://catfact.ninja
      endpoints:
        facts: /fact
        breeds: /breeds